### ISSUE TITLE
[FEATURE]  Service name should by default be included to structured logs 

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/ecs-dotnet#170] opened 2021-12-07 13:18 UTC
The APM enricher currently does not grab the service name from APM

Including this will provide a richer experience and better log correlation from the service overview page.

https://discuss.elastic.co/t/logs-do-not-appear-in-apm-although-correlation-info-is-present/289720/7

**Comment by russcam** [comment] 2021-12-08 02:25
Duplicate of #134

**Closed by russcam** 2021-12-08 02:25 UTC
Labels: enhancement
